### ISSUE TITLE
Umožnit uložení API key do konfiguračního souboru

### ISSUE THREAD

**Issue by tomassvec** [dvejsada/PID_integration#13]
Buď manuálně nebo jej uložit po prvním přidání automatizace a při dalších už jej nevyžadovat. Nebo jen pokud bude v konfiguraci (s manuálním zadáním), tak jej nevyžadovat. Je otravné jej stále dokolečka kopírovat když to člověk zkouší než najde správné parametry.

**Comment by dvejsada** [comment]
Při vytváření další instance integrace bude API kod automaticky převyplněn z první instance integrace.
