### ISSUE TITLE
Creation of custom card

### ISSUE THREAD

**Issue by dvejsada** [dvejsada/PID_integration#16]
I would appreciate help with creation of custom card to display departure board info from this component in useful way on dashboard.

**Comment by kristoficko** [comment]
Hi,
I'm trying to build this using the [flex-table-card](https://github.com/custom-cards/flex-table-card/tree/master) custom card. See [my current progress](https://pastebin.com/64ap4Ljg).

To-do is to use `modify:` (documented [here](https://github.com/custom-cards/flex-table-card/blob/master/docs/example-cfg-advanced-cell-formatting.md)) and Javacript expression to handle the delay column.

![image](https://github.com/dvejsada/PID_integration/assets/75023748/82e4ebb0-7e97-456e-91ed-6869a64f9670)

**Comment by dvejsada** [comment]
Hi, so to make the delay column work, you just replace the last part, i.e.:

```yaml
- data: delay.is_available , delay.minutes , delay.seconds
  name: MEŠKANIE (min)
```

with the following:

```yaml
- data: delay
  name: MEŠKANIE
  modify: |-
    if (x.is_available){
      x.minutes + " min."
    } else {
      "-"
    };
```

I will try to use your code to create some kind of template that can be used by anyone, if you do not mind.
