### ISSUE TITLE
Golemio API - formát URL

### ISSUE THREAD

**Issue by filiprafaj** [dvejsada/PID_integration#27]
I got an email from operátor ICT - afaik I only use golemio in this integration, so I guess it's related
> Dobrý den,
zaznamenali jsme, že voláte naše api.golemio.cz buď s přebytečným lomítkem na konci "/" nebo otazníkem "?" bez dalších parametrů. V rámci optimalizace našich služeb řešíme i kešování. V případě že ke stránce se přistupuju pod 2 různými URL, tak se pak i 2x kešuje. Plánujeme zavést automatický redirect (kod 301) na zkrácenou verzi, ale nejdříve chceme na to naše uživatele upozornit, aby to mohli upravit sami, protože některým by redirect nemusel fungovat.
Příklady nechtěných URL:
/v2/pid/departureboards/?ids=U693Z2P&total=3&preferredTimezone=Europe%2FPrague&minutesBefore=-9
/v2/pid/departureboards/
/v2/pid/departureboards/?
/v2/pid/departureboards?
/v2/vehiclepositions/gtfsrt/alerts.pb/
 Budeme rádi, když si to upravíte, protože tím budeme vědět, že se vám chování api nebude měnit.
Děkujeme

**Comment by dvejsada** [comment]
Yes, I received this e-mail as well. I will have a look into it.

**Comment by dvejsada** [comment]
CLosed by #28
