### ISSUE TITLE
Chyba při přidání zastávky Všenory ŽST

### ISSUE THREAD

**Issue by tomassvec** [dvejsada/PID_integration#6]
Při přidání zastávky 2279_1 (Všenory,žel.zast.) nevidím žádné entity. 
Verze: dea4a3109468a6eaa56d15e2bd8bce88d16b33a6

V Logu je chyba:
`2024-02-10 23:44:48.928 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up pid_integration platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/pid_integration/sensor.py", line 20, in async_setup_entry
    new_entities.append(DepartureSensor(departure_board.departures[i], departure_board))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pid_integration/sensor.py", line 44, in __init__
    self._state = self._departure_board.extra_attr[self._departure]["route"]["short_name"]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
IndexError: list index out of range
`

**Comment by dvejsada** [comment]
Díky, podívam se na to. Kolik odjezdů jste zadával do konfigurace?

**Comment by tomassvec** [comment]
Dělal jsem víc pokusů. Určitě 4 a 6. Nefungovalo ani pro jeden. Pokud bych si měl tipnout, tak problém bude spíše v tom, že se jedná o první pásmo (a je to mimo DPHlMP a mimo Prahu). Ale nevím.

**Comment by dvejsada** [comment]
Uz vidím čim to je - PID tam má jen linku 672 a ta jezdí jen v pracovních dnech. Integrace vyhledává odjezdy max dalších 24 hodin (kdy nic nejede). Musím tam pridat nějaký check, aby to nehodilo chybu. Díky.

**Comment by tomassvec** [comment]
Aha, takže chyba je i u mě. Já chci linku S7 (vlak). To jsou tedy asi zastávky 2279_301 a 2280_301 a ty se mi nedaří přidat vůbec.
`2024-02-11 00:22:46.123 ERROR (MainThread) [custom_components.pid_integration.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/pid_integration/config_flow.py", line 43, in async_step_user
    info = await validate_input(self.hass, user_input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pid_integration/config_flow.py", line 24, in validate_input
    result, stop = await hass.async_add_executor_job(ApiCall.authenticate, data[CONF_API_KEY], data[CONF_ID], data[CONF_DEP_NUM])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pid_integration/api_call.py", line 23, in authenticate
    title = reply["stops"][0]["stop_name"] + " " + reply["stops"][0]["platform_code"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
`

**Comment by dvejsada** [comment]
Opraveno (obě chyby). Problém u vlaku byl ten, že API neposkytovalo "platform_code". Jinak jsem prodloužil interval hledání na 7 dní, aby nevznikal problém s linkami, které o víkendu nejezdí. Do budoucna zvážím možnost si to nastavit individuálně.
