### ISSUE TITLE
Zadávání stop_id místo kombinace asw_node_id a asw_stop_id

### ISSUE THREAD

**Issue by tomassvec** [dvejsada/PID_integration#7]
Navrhuji zadávat na vstupu stop_id místo kombinace asw_node_id a asw_stop_id. Evidentně to je vzájemně převoditelné, ale snáze se to vyhledává i zadává. Je to i intuitivnější.

**Comment by dvejsada** [comment]
To jsem zkoušel jako první, bohužel API tam má zejména u metra nějakou chybu, že reálně vrací jinou stanici a žádné odjezdy. Pokusím se nějak uživatelsky zpříjemnit hledání parametru asw_Ids.

**Comment by dvejsada** [comment]
Doplněn soubor stops_list.txt do repa, kde lze aswIds stanice jednoduše vyhledat.
